# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "14ad4c0c55f1aaa04e18f0ed885a6857"
application_url = "https://example.com"
embedded = true
name = "excel-import-export"

[access_scopes]
scopes = "read_products,write_products,read_customers,write_customers,read_orders,read_inventory,write_inventory,read_draft_orders"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
